{% set name = "find-libpython" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/find_libpython-{{ version }}.tar.gz
  sha256: 46f9cdcd397ddb563b2d7592ded3796a41c1df5222443bd9d981721c906c03e6

build:
  entry_points:
    - find_libpython = find_libpython:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=43
  run:
    - python >={{ python_min }}

test:
  imports:
    - find_libpython
  commands:
    - pip check
    - find_libpython --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ktbarrett/find_libpython
  summary: Finds the libpython associated with your environment, wherever it may be hiding
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
